name: LazyRoadInGameDesigner
main: com.VeraLapsa.LRIGD.LazyRoadInGameDesigner
description: Plugin for making roads for LazyRoad.
version: ${project.version}
author: VeraLapsa
depend: [LazyRoad, WorldEdit]
softdepend: [LazyRoad, WorldEdit]
commands:
  lrdhelp:
    description: Help command for LazyRoad In-Game Designer
    usage: |
      /<command> [topic]
      Topics:[setroad, setstairs, setgrade, saveroad]
      Topics:[setkeepid, roadinfo, testroad, teststop]
      Topics:[setpillar, savepillar, testpillar, pillarinfo]
    permission: lrd.design
    permission-message: You don't have <permission>
  setroad:
    description: Sets up your WE selection as a road
    usage: /<command>
    permission: lrd.design
    permission-message: You don't have <permission>
  setstairs:
    description: Sets your we selection as the roads stairs.
    usage: |
      /<command>
    permission: lrd.design
    permission-message: You don't have <permission>
  setgrade:
    description: Sets how often the road's allowed to make stairs.
    usage: /<command> <positive number>
    permission: lrd.design
    permission-message: You don't have <permission>
  setkeepid:
    description: Sets the value keeper id.
    usage: |
      /<command> <BlockTypeID>
      This is what block you want to use to have
      the road ignore that space and not place air.
    permission: lrd.design
    permission-message: You don't have <permission>
  roadinfo:
    description: Displays the road's info.
    usage: |
      /<command>
    permission: lrd.design
    permission-message: You don't have <permission>
  saveroad:
    description: Saves your currently set road to to your desired name.
    usage: |
      /<command> <name>
      Can not contain spaces.
      This saves the road to the LazyRoad/roads folder
      and reloads LazyRoad.
    permission: lrd.design
    permission-message: You don't have <permission>
  testroad:
    description: Allows you to test your road before saving it.
    usage: |
      /<command>
    permission: lrd.design
    permission-message: You don't have <permission>
  teststop:
    description: Stops the test road and undoes it.
    usage: |
      /<command>
    permission: lrd.design
    permission-message: You don't have <permission>
  setpillar:
    description: Sets up your WE selection as a pillar
    usage: /<command>
    permission: lrd.design
    permission-message: You don't have <permission>
  savepillar:
    description: Saves your currently set pillar to to your desired name.
    usage: |
      /<command> <name>
      Can not contain spaces.
      This saves the road to the LazyRoad/pillars folder
      and reloads LazyRoad.
    permission: lrd.design
    permission-message: You don't have <permission>
  testpillar:
    description: Allows you to test your pillar before saving it.
    usage: |
      /<command> [road name]
      Plain /<command> tests the road with the currently set road.
      Otherwise "road name" is a name of a saved LazyRoad road.
    permission: lrd.design
    permission-message: You don't have <permission>
  pillarinfo:
    description: Displays the pillar's info.
    usage: |
      /<command>
    permission: lrd.design
    permission-message: You don't have <permission>
permissions:
  lrd.design:
    description: Allows use of the /lrd command.
    default: op